services:
  db:
    image: postgres:16
    ports:
      - '5433:5432'
    environment:
      POSTGRES_DB: cadmus
      POSTGRES_PASSWORD: postgres

  localstack:
    image: localstack/localstack:3
    ports:
      - '4566:4566'
    environment:
      - SERVICES=s3
      - DEFAULT_REGION=us-east-1

  server:
    build: ./packages/server
    ports:
      - '8080:8080'
    environment:
      - RUST_LOG=info
      - DATABASE_URL=postgres://postgres:postgres@db/cadmus
      - S3_ENDPOINT=http://localstack:4566
    depends_on:
      - db
      - localstack
